apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    acornsoft.io/workload-group-no: "2"
  generation: 3
  name: commerce-yr-product-v2
  namespace: commerce-yr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: commerce-yr-product
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: commerce-yr-product
        version: v2
    spec:
      containers:
      - image: 192.168.100.12/commerce-yr/commerce-yr-product-img:product-1
        imagePullPolicy: Always
        name: commerce-yr-product
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: "209715200"
          requests:
            cpu: 100m
            memory: "104857600"
        securityContext:
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: commerce-cocktail-t8ceb0dry5v7
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30